timedb:
  mem_limit: 96m
  image: mysql/mysql-server:5.6
  env_file:
    - .env.database
timeweb:
  mem_limit: 128m
  image: gobliip/time-tracker:0.0.1-SNAPSHOT
  ports:
    - "5022:5022"
  expose:
    - "5022"
  links:
    - timedb
  external_links:
    - eureka
    - docker_authweb_1:authweb
  env_file:
    - .env.database
    - .env